env:
  global:
    - secure: Mxu4VkrIdLzF4k2GpgY/vqTV7leV9pY8nHo+AkYriwp6HS6A5aZ1TSgXX3AeefrL4uKpzcMcJsZ9ie6lvo9dRRgKk2W5IM1hHtHLDvGApEKt9p1qN+x4VtVC50OIjJ0OCEQ+Lz84SiBwFkPEjOCZ2KJ/vwpbNiWCseHQK2Uso/w=
language: rust
script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
